# Generated by Django 5.2 on 2025-12-30 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('work', 'Work'), ('study', 'Study'), ('personal', 'Personal'), ('health', 'Health'), ('social', 'Social'), ('hobby', 'Hobby'), ('self_care', 'Self Care'), ('other', 'Other')], max_length=50),
        ),
    ]
