# Generated by Django 5.2 on 2025-05-06 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moodentry',
            name='diet_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='moodentry',
            name='exercised',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='moodentry',
            name='water_intake',
            field=models.PositiveIntegerField(default=0, help_text='Cups of water drank'),
        ),
    ]
