# Generated by Django 5.2 on 2025-05-20 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='points',
            field=models.PositiveIntegerField(default=10, help_text='Points awarded when this task is completed.'),
        ),
        migrations.AddField(
            model_name='user',
            name='points',
            field=models.PositiveIntegerField(default=0, help_text='Total reward points collected by the user.'),
        ),
    ]
