# Generated by Django 5.2 on 2025-05-20 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_task_points_user_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='rewards',
            name='claimed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rewards',
            name='is_claimed',
            field=models.BooleanField(default=False),
        ),
    ]
