# Generated by Django 5.2 on 2025-05-21 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_aisummary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='font_size',
        ),
        migrations.RemoveField(
            model_name='user',
            name='theme',
        ),
    ]
