# Generated by Django 5.2 on 2025-05-23 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_user_font_size_remove_user_theme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='color',
        ),
    ]
