# Generated by Django 5.2 on 2025-05-23 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_category_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='actual_completed_at',
        ),
        migrations.RemoveField(
            model_name='task',
            name='estimated_completed_at',
        ),
    ]
